@root_url = http://localhost:5277/games

### GET all games
GET {{root_url}}

### GET a game by ID
GET {{root_url}}/cfd98d03-3770-4543-a0a9-090d19fbfaf1

### POST a new game
POST {{root_url}}
Content-Type: application/json

{
  "title": "Red Dead Redemption 2",
  "genre": "",
  "price": 149.99,
  "releaseDate": "2018-10-26"
}