@root_url_games = http://localhost:5277/games
@root_url_genres = http://localhost:5277/genres

### GET all games
GET {{root_url_games}}

### GET a game by ID
GET {{root_url_games}}/4f8bae62-4ac9-44bc-820a-a454d78378fe

### POST a new game
POST {{root_url_games}}
Content-Type: application/json

{
  "title": "Red Dead Redemption 22",
  "genreId": "bb553af0-8832-42ae-8e72-c915efbf084d",
  "price": 39.99,
  "releaseDate": "2018-10-26",
  "description": "An epic tale of life in America’s unforgiving heartland."
}

### PUT to update a game
PUT {{root_url_games}}/7b6d821f-96a9-41ee-9c74-49eb35343493
Content-Type: application/json

{
  "title": "Knight Online",
  "genreId": "f063099a-aa4f-463b-80d2-14173ead95a8",
  "price": 1.99,
  "releaseDate": "2002-01-01",
  "description": "A free-to-play fantasy MMORPG."
}

### DELETE a game
DELETE {{root_url_games}}/2c913a52-68a5-4dbb-8b3a-8211a7f760f5

### GET all genres
GET {{root_url_genres}}