@root_url_games = http://localhost:5277/games
@root_url_genres = http://localhost:5277/genres

### GET all games
GET {{root_url_games}}

### GET a game by ID
GET {{root_url_games}}/e358b183-7b33-40ab-9d9e-09799f83f3db

### POST a new game
POST {{root_url_games}}
Content-Type: application/json

{
  "title": "Knight Online",
  "genreId": "3e37bf3b-66f4-4461-b9a4-8a71a3407424",
  "price": 9.99,
  "releaseDate": "2018-10-26",
  "description": "An epic tale of life in America’s unforgiving heartland."
}

### PUT to update a game
PUT {{root_url_games}}/e5ac33cd-6e08-4aeb-84b6-d187ed5099c3
Content-Type: application/json

{
  "title": "Knight Online",
  "genreId": "3e37bf3b-66f4-4461-b9a4-8a71a3407424",
  "price": 21.99,
  "releaseDate": "2002-01-01",
  "description": "A free-to-play fantasy MMORPG."
}

### DELETE a game
DELETE {{root_url_games}}/45959751-5dcd-4d61-a37f-156b562b316f

### GET all genres
GET {{root_url_genres}}